Members only
prolajumokeoni/members_only pull request #3
Opened 2021-07-03 09:25 UTC by prolajumokeoni

In this project:
- Created a Post model and a Posts controller
- Users can add post and comments
- Only when signed in can users create post
- Authenticated users with devise

2021-07-03 11:58 UTC, SajjadAhmad14 commented on app/controllers/posts_controller.rb
> +    # @post = Post.new(post_params)
Please remove commented code from here.

2021-07-03 12:00 UTC, SajjadAhmad14 commented on app/views/devise/mailer/email_changed.html.erb
> +<% end %>
Please move this logic to app/helpers. [ OPTIONAL ]

2021-07-03 12:02 UTC, SajjadAhmad14 commented on app/views/devise/shared/_error_messages.html.erb
> +<% end %>
Please move this logic to app/helpers. [ OPTIONAL ]

2021-07-03 12:02 UTC, SajjadAhmad14 commented on app/views/posts/_form.html.erb
> +    </div>
Please move this logic to app/helpers. [ OPTIONAL ]

2021-07-03 12:03 UTC, SajjadAhmad14 commented on app/views/posts/index.html.erb
> +        <% end %>
Please move this logic to app/helpers. [ OPTIONAL ]

2021-07-03 12:03 UTC, SajjadAhmad14 commented on app/views/shared/_nav.html.erb
> +        <% end %>
Please move this logic to app/helpers. [ OPTIONAL ]

2021-07-03 12:06 UTC, SajjadAhmad14 requested changes
# Changes Required :recycle:
> "Change is inevitable. Change is constant. -Benjamin Disraeli"
## Hello, you have been doing a tremendous job so far :ok_hand:
## To Highlight 🎉
- [ ] Git flow is properly used.
- [ ] README has step-by-step instructions to run the project locally.
## To Improve 🙏
- [ ] Please remove commented code. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/section/debugging_requirement.png).
- [ ] Login user should see post author name not user_id. Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/signed_in_can_see_author_requirement.png).
- [ ] App should protect its routes and only expose to routes that are used.  It creates the application routes using resources :posts, only: [:new, :create, :index].
- [ ] User should not be able to access posts/new route if he's not signed in.
- [ ] App should use before_action to restrict access to the :new and :create methods (uses ApplicationController helper method). Please see this [screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/authentication/before_action_requirement.png).
# Optional
- [ ] You can deploy the app to Netlify or Heroku.
- [ ] Views should be completely separate from app logic. You can move view-related logic to app/helpers.
### Happy Coding ☺️
## If you have any questions you can comment here in this PR or can always connect with me on slack ( @Sajjad Ahmad ).

2021-07-05 10:05 UTC, NtwaliHeritier approved these changes
### **STATUS: APPROVED👍️👍️👍️**

Hello @prolajumokeoni 

Great work making changes👏️👏️👏️

You can merge👍️👍️

Happy coding💻️💻️💻️

2021-07-05 10:16 UTC, closed without merging